services:
  backend:
    build:
        dockerfile: ./Dockerfile
    container_name: backend_tfidf
    env_file:
      - path: .env-template
        required: true
      - path: .env
        required: false
    ports:
      - "${TFIDF__RUN__PORT}:${TFIDF__RUN__PORT}"